draw_self()
draw_set_halign(fa_left)
draw_set_valign(fa_top)
draw_set_colour(c_white)
draw_set_alpha(1)
draw_text_ext(bbox_left + 15, bbox_top + 15, text, 20, sprite_width - 30)
draw_set_halign(fa_right)
draw_set_valign(fa_bottom)
draw_text(bbox_right - 15, bbox_bottom - 15, "Click to close")